return {
  'folke/which-key.nvim',
  event = 'VimEnter',
  keys = {
    { '?', function() require('which-key').show({ global = true }) end, desc = 'Which Key' },
  },
  opts = {
    icons = {
      mappings = vim.g.have_nerd_font,
      keys = vim.g.have_nerd_font and {} or {
        Up = '<Up> ',
        Down = '<Down> ',
        Left = '<Left> ',
        Right = '<Right> ',
        C = '<C-…> ',
        M = '<M-…> ',
        D = '<D-…> ',
        S = '<S-…> ',
        CR = '<CR> ',
        Esc = '<Esc> ',
        ScrollWheelDown = '<ScrollWheelDown> ',
        ScrollWheelUp = '<ScrollWheelUp> ',
        NL = '<NL> ',
        BS = '<BS> ',
        Space = '<Space> ',
        Tab = '<Tab> ',
        F1 = '<F1>',
        F2 = '<F2>',
        F3 = '<F3>',
        F4 = '<F4>',
        F5 = '<F5>',
        F6 = '<F6>',
        F7 = '<F7>',
        F8 = '<F8>',
        F9 = '<F9>',
        F10 = '<F10>',
        F11 = '<F11>',
        F12 = '<F12>',
      },
    },
    spec = {
      { '<leader>c', group = '[C]ode', mode = { 'n', 'x' } },
      { '<leader>d', group = '[D]ocument' },
      { '<leader>r', group = '[R]ename' },
      { '<leader>s', group = '[S]earch' },
      { '<leader>w', group = '[W]orkspace' },
      { '<leader>t', group = '[T]oggle' },
      { '<leader>h', group = 'Git [H]unk', mode = { 'n', 'v' } },
      { '<leader>b', group = '[B]uffer' },
      { '<leader>D', group = '[D]ebug' },
      { '<leader>g', group = '[G]it' },
      { '<leader>f', group = '[F]ormat / [F]loat file', mode = { 'n', 'x' } },
      { '<leader>n', group = '[N]eotree' },
      { '<leader>o', group = '[O]penCode', mode = { 'n', 'x' } },
      { '<leader>B', group = 'De[B]ug', mode = { 'n', 'x' } },
      { 'go', group = 'Send range to OpenCode', mode = { 'n', 'x' } },
      { 'tt', group = 'Toggle NeoTree', mode = 'n' },
      { '<leader>p', group = '[P]review image' },
    },
  },
}
